window.SUPERVISION_DATA = (function buildData() {
  const hourLabels = Array.from({ length: 24 }, (_, i) => `${String(i).padStart(2, "0")}:00`);

  function round(value, decimals) {
    const factor = 10 ** decimals;
    return Math.round(value * factor) / factor;
  }

  function makeSignal(base, amplitude, drift, decimals, phase, spikeAt, spikeValue) {
    return hourLabels.map((_, index) => {
      const wave = Math.sin((index + phase) * 0.45) * amplitude;
      const trend = drift * index;
      const pulse = index === spikeAt ? spikeValue : 0;
      return round(base + wave + trend + pulse, decimals);
    });
  }

  function createEquipment(config) {
    const tempSeries = makeSignal(config.baseTemp, config.ampTemp, config.driftTemp, 1, config.phase, config.spikeAt, config.tempSpike || 0);
    const pressureSeries = makeSignal(config.basePressure, config.ampPressure, config.driftPressure, 2, config.phase + 2, config.spikeAt, config.pressureSpike || 0);
    const powerSeries = makeSignal(config.basePower, config.ampPower, config.driftPower, 0, config.phase + 1, config.spikeAt, config.powerSpike || 0);

    return {
      id: config.id,
      nom: config.nom,
      type: config.type,
      zone: config.zone,
      statut: config.statut,
      left: config.left,
      top: config.top,
      service: config.service,
      fabricant: config.fabricant,
      modele: config.modele,
      serial: config.serial,
      metrics: {
        pression: `${pressureSeries[pressureSeries.length - 1]} bar`,
        temperature: `${tempSeries[tempSeries.length - 1]} C`,
        charge: `${config.charge} %`,
        kw: `${powerSeries[powerSeries.length - 1]} kW`
      },
      maintenance: {
        derniere: config.maintenanceDerniere,
        prochaine: config.maintenanceProchaine,
        statut: config.maintenanceStatut,
        technicien: config.technicien,
        alertes: config.alertes
      },
      documents: config.documents,
      courbes: {
        labels: hourLabels,
        temperature: [{ nom: "Temp C", couleur: "#4ade80", valeurs: tempSeries }],
        pression: [{ nom: "Pression bar", couleur: "#fb923c", valeurs: pressureSeries }],
        puissance: [{ nom: "Puissance kW", couleur: "#60a5fa", valeurs: powerSeries }]
      }
    };
  }

  const equipments = [
    createEquipment({
      id: "oil",
      nom: "Separateur d'huile",
      type: "Separation",
      zone: "Ligne frigorifique A",
      statut: "actif",
      left: "42%",
      top: "38%",
      service: "Production",
      fabricant: "FrigoTech",
      modele: "SO-220",
      serial: "SO-220-2023-117",
      charge: 68,
      baseTemp: -17.9,
      ampTemp: 1.7,
      driftTemp: 0.05,
      basePressure: 2.0,
      ampPressure: 0.2,
      driftPressure: 0.01,
      basePower: 46,
      ampPower: 4,
      driftPower: 0.25,
      phase: 1,
      spikeAt: 14,
      maintenanceDerniere: "2026-01-12",
      maintenanceProchaine: "2026-03-15",
      maintenanceStatut: "A jour",
      technicien: "M. Dupont",
      alertes: ["Aucune alarme active", "Vibration dans la plage nominale"],
      documents: [
        { nom: "PV intervention Janvier", type: "PV", date: "2026-01-12" },
        { nom: "Releve pression semaine 06", type: "Releve", date: "2026-02-08" },
        { nom: "Controle reglementaire annuel", type: "Reglementaire", date: "2025-11-21" }
      ]
    }),
    createEquipment({
      id: "pump1",
      nom: "Pompe 1",
      type: "Pompe",
      zone: "Circuit secondaire",
      statut: "maintenance",
      left: "48%",
      top: "56%",
      service: "Maintenance",
      fabricant: "HydroSys",
      modele: "P-900",
      serial: "P900-2019-03",
      charge: 34,
      baseTemp: -20.2,
      ampTemp: 1.1,
      driftTemp: 0.03,
      basePressure: 3.4,
      ampPressure: 0.36,
      driftPressure: 0.02,
      basePower: 33,
      ampPower: 4,
      driftPower: 0.22,
      phase: 3,
      spikeAt: 18,
      pressureSpike: 0.18,
      maintenanceDerniere: "2025-12-18",
      maintenanceProchaine: "2026-02-18",
      maintenanceStatut: "Intervention planifiee",
      technicien: "Mme Leroy",
      alertes: ["Maintenance preventive dans 7 jours", "Controle garniture mecanique requis"],
      documents: [
        { nom: "Bon de travail BT-441", type: "PV", date: "2026-02-01" },
        { nom: "Releve vibration S05", type: "Releve", date: "2026-02-06" },
        { nom: "Notice constructeur", type: "Reglementaire", date: "2024-04-02" }
      ]
    }),
    createEquipment({
      id: "comp1",
      nom: "Compresseur 1",
      type: "Compresseur",
      zone: "Salle machine",
      statut: "alarme",
      left: "61%",
      top: "44%",
      service: "Production",
      fabricant: "NordComp",
      modele: "NC-45",
      serial: "NC45-2020-88",
      charge: 91,
      baseTemp: -13.2,
      ampTemp: 1.6,
      driftTemp: 0.07,
      basePressure: 4.6,
      ampPressure: 0.35,
      driftPressure: 0.03,
      basePower: 96,
      ampPower: 10,
      driftPower: 0.7,
      phase: 0,
      spikeAt: 13,
      pressureSpike: 0.35,
      powerSpike: 12,
      maintenanceDerniere: "2025-11-02",
      maintenanceProchaine: "2026-02-25",
      maintenanceStatut: "Alerte haute pression",
      technicien: "Equipe astreinte",
      alertes: ["Depassement seuil pression a 13:00", "Inspection immediate recommandee"],
      documents: [
        { nom: "PV controle securite", type: "PV", date: "2025-11-02" },
        { nom: "Historique alarmes Fevrier", type: "Releve", date: "2026-02-10" },
        { nom: "Procedure urgence compresseur", type: "Reglementaire", date: "2025-06-16" }
      ]
    }),
    createEquipment({
      id: "cond1",
      nom: "Condenseur",
      type: "Echangeur",
      zone: "Toiture",
      statut: "actif",
      left: "70%",
      top: "29%",
      service: "Production",
      fabricant: "ThermoFlow",
      modele: "CD-120",
      serial: "CD120-2022-44",
      charge: 74,
      baseTemp: -8.4,
      ampTemp: 1.2,
      driftTemp: 0.01,
      basePressure: 2.8,
      ampPressure: 0.18,
      driftPressure: 0.015,
      basePower: 58,
      ampPower: 5,
      driftPower: 0.2,
      phase: 5,
      spikeAt: 19,
      maintenanceDerniere: "2026-01-28",
      maintenanceProchaine: "2026-04-20",
      maintenanceStatut: "A jour",
      technicien: "M. Nguyen",
      alertes: ["Aucune alerte critique", "Nettoyage ailettes planifie"],
      documents: [
        { nom: "Rapport performance condenseur", type: "Releve", date: "2026-02-09" },
        { nom: "PV nettoyage ailettes", type: "PV", date: "2026-01-28" },
        { nom: "Plan maintenance trimestriel", type: "Reglementaire", date: "2026-01-01" }
      ]
    }),
    createEquipment({
      id: "evap1",
      nom: "Evaporateur",
      type: "Echangeur",
      zone: "Tunnel froid",
      statut: "actif",
      left: "33%",
      top: "64%",
      service: "Production",
      fabricant: "CryoAir",
      modele: "EV-640",
      serial: "EV640-2021-90",
      charge: 62,
      baseTemp: -24.5,
      ampTemp: 1.9,
      driftTemp: 0.04,
      basePressure: 1.65,
      ampPressure: 0.14,
      driftPressure: 0.006,
      basePower: 40,
      ampPower: 4,
      driftPower: 0.1,
      phase: 2,
      spikeAt: 16,
      tempSpike: -0.8,
      maintenanceDerniere: "2026-01-10",
      maintenanceProchaine: "2026-03-02",
      maintenanceStatut: "A surveiller",
      technicien: "Mme Roux",
      alertes: ["Degivrage manuel observe", "Controle ventilateurs recommande"],
      documents: [
        { nom: "Releve degivrage", type: "Releve", date: "2026-02-10" },
        { nom: "PV controle ventilateurs", type: "PV", date: "2026-01-10" },
        { nom: "Consignes tunnel froid", type: "Reglementaire", date: "2025-09-12" }
      ]
    }),
    createEquipment({
      id: "valve1",
      nom: "Vanne de detente",
      type: "Vanne",
      zone: "Ligne liquide",
      statut: "maintenance",
      left: "55%",
      top: "63%",
      service: "Maintenance",
      fabricant: "Valvex",
      modele: "VD-45",
      serial: "VD45-2018-11",
      charge: 29,
      baseTemp: -18.8,
      ampTemp: 1.4,
      driftTemp: 0.02,
      basePressure: 2.25,
      ampPressure: 0.22,
      driftPressure: 0.008,
      basePower: 22,
      ampPower: 3,
      driftPower: 0.08,
      phase: 4,
      spikeAt: 10,
      pressureSpike: -0.24,
      maintenanceDerniere: "2025-12-02",
      maintenanceProchaine: "2026-02-20",
      maintenanceStatut: "Kit joints a remplacer",
      technicien: "M. Vidal",
      alertes: ["Derive de regulation detectee", "Intervention de recalibrage prevue"],
      documents: [
        { nom: "PV calibrage vanne", type: "PV", date: "2025-12-02" },
        { nom: "Courbe ouverture 24h", type: "Releve", date: "2026-02-11" },
        { nom: "Procedure remplacement joints", type: "Reglementaire", date: "2024-10-15" }
      ]
    }),
    createEquipment({
      id: "tank1",
      nom: "Reservoir liquide",
      type: "Reservoir",
      zone: "Zone stockage",
      statut: "actif",
      left: "24%",
      top: "49%",
      service: "Production",
      fabricant: "StorCool",
      modele: "RL-500",
      serial: "RL500-2017-06",
      charge: 81,
      baseTemp: -9.5,
      ampTemp: 0.9,
      driftTemp: 0.01,
      basePressure: 1.85,
      ampPressure: 0.1,
      driftPressure: 0.004,
      basePower: 15,
      ampPower: 2,
      driftPower: 0.03,
      phase: 6,
      spikeAt: 20,
      maintenanceDerniere: "2025-10-30",
      maintenanceProchaine: "2026-04-10",
      maintenanceStatut: "A jour",
      technicien: "M. Simon",
      alertes: ["Niveau stable sur 24h", "Aucune variation anormale"],
      documents: [
        { nom: "PV inspection reservoir", type: "PV", date: "2025-10-30" },
        { nom: "Releve niveau hebdo", type: "Releve", date: "2026-02-09" },
        { nom: "Attestation soupape", type: "Reglementaire", date: "2025-07-04" }
      ]
    }),
    createEquipment({
      id: "pump2",
      nom: "Pompe 2",
      type: "Pompe",
      zone: "Circuit secondaire",
      statut: "actif",
      left: "52%",
      top: "71%",
      service: "Production",
      fabricant: "HydroSys",
      modele: "P-910",
      serial: "P910-2020-71",
      charge: 57,
      baseTemp: -17.4,
      ampTemp: 1.0,
      driftTemp: 0.025,
      basePressure: 3.05,
      ampPressure: 0.2,
      driftPressure: 0.013,
      basePower: 41,
      ampPower: 4,
      driftPower: 0.17,
      phase: 7,
      spikeAt: 15,
      maintenanceDerniere: "2026-01-20",
      maintenanceProchaine: "2026-03-30",
      maintenanceStatut: "A jour",
      technicien: "Mme Leroy",
      alertes: ["Rendement nominal", "Aucune alerte active"],
      documents: [
        { nom: "PV graissage", type: "PV", date: "2026-01-20" },
        { nom: "Releve conso electrique", type: "Releve", date: "2026-02-11" },
        { nom: "Notice maintenance P-910", type: "Reglementaire", date: "2025-08-01" }
      ]
    }),
    createEquipment({
      id: "filter1",
      nom: "Filtre deshydrateur",
      type: "Filtration",
      zone: "Ligne liquide",
      statut: "alarme",
      left: "64%",
      top: "58%",
      service: "Production",
      fabricant: "CleanCool",
      modele: "FD-200",
      serial: "FD200-2019-55",
      charge: 87,
      baseTemp: -14.2,
      ampTemp: 1.1,
      driftTemp: 0.05,
      basePressure: 3.8,
      ampPressure: 0.26,
      driftPressure: 0.022,
      basePower: 50,
      ampPower: 5,
      driftPower: 0.28,
      phase: 8,
      spikeAt: 17,
      pressureSpike: 0.42,
      maintenanceDerniere: "2025-09-14",
      maintenanceProchaine: "2026-02-14",
      maintenanceStatut: "Delta P eleve",
      technicien: "Equipe astreinte",
      alertes: ["Colmatage suspecte", "Remplacement cartouche sous 72h"],
      documents: [
        { nom: "PV changement cartouche precedent", type: "PV", date: "2025-09-14" },
        { nom: "Historique delta pression", type: "Releve", date: "2026-02-11" },
        { nom: "Procedure securite filtration", type: "Reglementaire", date: "2025-05-22" }
      ]
    }),
    createEquipment({
      id: "comp2",
      nom: "Compresseur 2",
      type: "Compresseur",
      zone: "Salle machine",
      statut: "actif",
      left: "74%",
      top: "47%",
      service: "Production",
      fabricant: "NordComp",
      modele: "NC-52",
      serial: "NC52-2024-12",
      charge: 77,
      baseTemp: -12.8,
      ampTemp: 1.4,
      driftTemp: 0.06,
      basePressure: 4.3,
      ampPressure: 0.28,
      driftPressure: 0.02,
      basePower: 84,
      ampPower: 8,
      driftPower: 0.52,
      phase: 9,
      spikeAt: 12,
      powerSpike: 10,
      maintenanceDerniere: "2026-01-08",
      maintenanceProchaine: "2026-03-12",
      maintenanceStatut: "A jour",
      technicien: "M. Bernard",
      alertes: ["Performance stable", "Controle vibration sous seuil"],
      documents: [
        { nom: "PV commissioning", type: "PV", date: "2026-01-08" },
        { nom: "Releve rendement 24h", type: "Releve", date: "2026-02-11" },
        { nom: "Plan d'entretien NC-52", type: "Reglementaire", date: "2026-01-02" }
      ]
    })
  ];

  return { equipments };
})();
